### ISSUE TITLE
after "yarn run electron:release", run "Jellyfin Client" , I can't login. The log is:

### ISSUE THREAD

**Issue by demoictech** [EraYaN/jellyfin-webng#48]
DEMO-STRING (your resumable items):

{"Items":[],"TotalRecordCount":0}

The log file is:

[2019-12-26 21:42:59.872 +08:00] [INF] FFmpeg: SetByArgument: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2019-12-26 21:42:59.875 +08:00] [INF] ServerId: "0033480f23c342cd9fd9f1cb9af0603e"
[2019-12-26 21:43:00.310 +08:00] [INF] Executed all pre-startup entry points in 0:00:00.4136701
[2019-12-26 21:43:00.310 +08:00] [INF] Core startup complete
[2019-12-26 21:43:00.986 +08:00] [INF] Watching directory /data_dir/disk_sdb1/media_home/music_home
[2019-12-26 21:43:00.986 +08:00] [INF] Watching directory /data_dir/disk_sdb1/media_home/image_home
[2019-12-26 21:43:00.989 +08:00] [INF] Watching directory /data_dir/disk_sdb1/media_home/video_home
[2019-12-26 21:43:01.080 +08:00] [INF] Executed all post-startup entry points in 0:00:00.7687639
[2019-12-26 21:43:01.129 +08:00] [INF] Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.1.108"
[2019-12-26 21:43:02.761 +08:00] [INF] "StartupTrigger" fired for task: "Check for plugin updates"
[2019-12-26 21:43:02.766 +08:00] [INF] Queueing task "PluginUpdateTask"
[2019-12-26 21:43:02.782 +08:00] [INF] Executing "Check for plugin updates" 
[2019-12-26 21:43:03.507 +08:00] [WRN] HTTP Response 204 to "192.168.1.107". Time (slow): 0:00:01.0435733. "http://192.168.1.108:8096/Sessions/Playing/Progress"
[2019-12-26 21:43:07.086 +08:00] [INF] "Check for plugin updates" Completed after 0 minute(s) and 4 seconds
[2019-12-26 21:43:07.113 +08:00] [INF] ExecuteQueuedTasks
[2019-12-26 21:43:10.025 +08:00] [ERR] Error creating http port map
MediaBrowser.Model.Net.HttpException: Internal Server Error
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMap(Mapping mapping)
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.CreateRules(INatDevice device)
[2019-12-26 21:43:27.044 +08:00] [INF] WS "http://192.168.1.108:8096/socket?api_key=37cd69afe6a84f18a2746e8b0fba108a&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NzEuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83MS4wfDE1NzczNjQyMTY2OTQ1". UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
[2019-12-26 21:43:28.950 +08:00] [INF] WS "http://192.168.1.108:8096/socket?api_key=37cd69afe6a84f18a2746e8b0fba108a&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NzEuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83MS4wfDE1NzczNjQyMTY2OTQ1". UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
[2019-12-26 21:44:12.678 +08:00] [INF] Authentication request for "demo" "has succeeded".
[2019-12-26 21:44:12.682 +08:00] [INF] Reissuing access token: aa7e93510ab942fe9fe91dcced953752

**Comment by crobibero** [comment]
That is you logging in successfully, this app doesn't have any real functionality yet

**Comment by demoictech** [comment]
> 
> 
> That is you logging in successfully, this app doesn't have any real functionality yet

Yes, you are right. What should I do next? Thanks.

**Comment by anthonylavado** [comment]
@demoictech That’s it. There’s nothing else right now. The app still needs to be worked on. There’s nothing else you can do it the app. It can only log in. It doesn’t show or play anything yet.
